In [1]:
# import galstreams
# mws = galstreams.MWStreams(verbose=False)

import sys, pickle, os
from importlib import reload
from tqdm import tqdm, trange

import numpy as np, pandas as pd

import matplotlib.pyplot as plt
from matplotlib.colors import SymLogNorm, LogNorm

import agama 
Gyr_to_AgamaTime = 1.0227 # 1 Gyr in Agama time units (kpc/(km/s))
import nbody_streams.agama_helper as ah

import emcee
import corner

from astropy import units as u
import astropy.coordinates as coord
from astropy.coordinates import Galactocentric, ICRS, CartesianDifferential, CartesianRepresentation
from astropy import table

In [2]:
os.getcwd()

'/astro/users/shriyp/mw_gpotential_streams/notebooks'

In [3]:
sys.path.append('../scripts/')
from coordinate_utils import get_rotation_matrix, sf_to_icrs, icrs_to_sf
from generate_sim_stream import create_stream_particle_spray
from stream_likelihood import log_likelihood, make_spline, log_prior, log_probability
from stream_data_utils import read_in_data

In [4]:
# Define file paths
BASE_POT_PATH = '../potential_files'
potMW_path = os.path.join(BASE_POT_PATH, 'McMillan17_nora.ini')
potLMC_path = os.path.join(BASE_POT_PATH, 'LMC_nora.ini')
accMW_path = os.path.join(BASE_POT_PATH, 'accMW')
trajLMC_path = os.path.join(BASE_POT_PATH, 'trajLMC')

## potential models to load
potMW = agama.Potential(file=potMW_path)
accMW = np.loadtxt(accMW_path)
trajLMC = np.loadtxt(trajLMC_path)
potacc  = agama.Potential(type='UniformAcceleration', file=accMW)
potLMC  = agama.Potential(file=potLMC_path)
potLMCm = agama.Potential(potential=potLMC, center=trajLMC)
potTotal= agama.Potential(potMW, potLMCm, potacc)

In [5]:
aau_member_path = '../data/aau_members.csv'
aau_distance_path = '../data/aau_bhb_rrl.csv'

aau_table = pd.read_csv(aau_member_path)
aau_bhb_rrl_data = pd.read_csv(aau_distance_path)

aau_bhb_rrl_data.columns = aau_bhb_rrl_data.columns.str.lower()

df_aau, prog_pars_aau, prog_pars_icrs_aau, df_distance_aau = read_in_data(aau_table, 'distance_modulus', aau_bhb_rrl_data)

In [6]:
print(prog_pars_aau[2])
prog_pars_aau[2] = 10**((prog_pars_aau[2] - 10) / 5)
prog_pars_icrs_aau[2] = 10**((prog_pars_icrs_aau[2] - 10) / 5)

phi1_pos = 0
prog_pars_aau[0] = phi1_pos  #FIXING PHI1 @ specified location on stream-track

print(prog_pars_aau)

16.744050585569173
[0, 0.8556910645897031, 22.325958704826597, -0.1891601021018523, -0.9768522127958916, -114.15299941957676]


In [7]:
data_dict_aau = dict(
    phi1_obs = df_aau['phi1'].values,
    phi1_obs_dist = df_distance_aau['phi1'].values,
    phi2_obs = df_aau['phi2'].values,
    rv_obs = df_aau['vel_calib'].values,
    rv_obs_errors = df_aau['vel_calib_std'].values,
    dist_obs = 10**((df_distance_aau['distance_modulus'].values - 10) / 5),
    dist_obs_errors = 10**((df_distance_aau['distance_modulus'].values - 10) / 5) * 0.1,
    pmra_cosdec_obs = df_aau['pmra'].values,
    pmra_cosdec_obs_errors = df_aau['pmra_error'].values,
    pmdec_obs = df_aau['pmdec'].values,
    pmdec_obs_errors = df_aau['pmdec_error'].values,
)

In [8]:
#Constructing stream progenitor present-day coordinates and information

prog_mass, prog_scaleradius =  20_000, 10/1_000 # Msun, kpc

num_particles = 2_000

Age_stream_inGyr = 5.0

R = np.array([[ 0.83282408,  0.30044863, -0.46490286],
 [-0.52284461,  0.70275989, -0.48245419],
 [ 0.18176238,  0.64487142,  0.74236331]])

aau_rot_matrix = u.Quantity(R, unit=u.dimensionless_unscaled)
#aau_rot_matrix = get_rotation_matrix('AAU-ATLAS-L21', mws = mws)

print(aau_rot_matrix)


[[ 0.83282408  0.30044863 -0.46490286]
 [-0.52284461  0.70275989 -0.48245419]
 [ 0.18176238  0.64487142  0.74236331]]


In [9]:
log_probability(prog_pars_aau[1:], data_dict_aau, potTotal, prog_mass, prog_scaleradius, Age_stream_inGyr, num_particles, aau_rot_matrix)

np.float64(-283786.58144301316)

In [10]:
print(data_dict_aau.keys())

dict_keys(['phi1_obs', 'phi1_obs_dist', 'phi2_obs', 'rv_obs', 'rv_obs_errors', 'dist_obs', 'dist_obs_errors', 'pmra_cosdec_obs', 'pmra_cosdec_obs_errors', 'pmdec_obs', 'pmdec_obs_errors'])


In [11]:
#MCMC fit
nwalkers = 200
niter = 2500

#Taking a fraction of the prior range 
initial = prog_pars_aau[1:]
ndim = len(initial)
p0 = [np.array(initial) + 1e-3 * np.random.randn(ndim) for i in range(nwalkers)]

data = (data_dict_aau, potTotal, prog_mass, prog_scaleradius, Age_stream_inGyr, num_particles, aau_rot_matrix)

def main(p0,nwalkers,niter,ndim,log_probability,data, nburnin=500):
    sampler = emcee.EnsembleSampler(nwalkers, ndim, log_probability, args=data)
    print("Running burn-in...")
    p0, _, _ = sampler.run_mcmc(p0, nburnin, progress = True)
    print(f"Mean acceptance fraction: {np.mean(sampler.acceptance_fraction):.3f}") #tells us how much of the burn-ins were accepted; 0.2-0.5 good
    sampler.reset()

    print("Running production...")
    pos, prob, state = sampler.run_mcmc(p0, niter, progress = True)

    return sampler, pos, prob, state

In [12]:
print(prog_pars_aau)

[0, 0.8556910645897031, 22.325958704826597, -0.1891601021018523, -0.9768522127958916, -114.15299941957676]


In [13]:
print(log_probability(initial, *data))

-283786.58144301316
